# Generated by Django 4.2.4 on 2023-08-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subtitulo',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
